using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using TestGenerator.Core.CodeGenerators.Models;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace TestGenerator.Core.CodeGenerators.Builders;

internal class TestMethodBuilder
{
    private const string ArrangeComment = "// Arrange";
    private const string ActComment = "// Act";
    private const string AssertComment = "// Assert";
    private const string TestAttributeName = "Test";
    private const string TestClassFieldName = "_myClassUnderTest";
    private const string ActualVariableName = "actual";
    private const string ExpectedVariableName = "expected";
    private const string FailMessage = "autogenerated";

    public MethodDeclarationSyntax Build(MethodInfo methodInfo, List<DependencyInfo> dependencies)
    {
        List<StatementSyntax> arrangeStatements = CreateArrangeStatements(methodInfo, dependencies);
        List<StatementSyntax> actStatements = CreateActStatements(methodInfo);
        List<StatementSyntax> assertStatements = CreateAssertStatements(methodInfo, dependencies);

        List<StatementSyntax> allStatements = CombineStatements(arrangeStatements, actStatements, assertStatements);
        List<StatementSyntax> finalStatements = FilterCommentStatements(allStatements);

        string methodName = $"{methodInfo.Name}Test";

        return CreateMethodDeclaration(methodName, finalStatements);
    }

    private List<StatementSyntax> CombineStatements(
        List<StatementSyntax> arrange,
        List<StatementSyntax> act,
        List<StatementSyntax> assert)
    {
        var statements = new List<StatementSyntax>();

        if (arrange.Count != 0)
        {
            statements.AddRange(arrange);
            statements.Add(CreateCommentStatement(ArrangeComment));
        }

        statements.Add(CreateCommentStatement(ActComment));
        statements.AddRange(act);
        statements.Add(CreateCommentStatement(AssertComment));
        statements.AddRange(assert);

        return statements;
    }

    private List<StatementSyntax> FilterCommentStatements(List<StatementSyntax> statements)
    {
        return statements
            .Where((StatementSyntax s) => s is not ExpressionStatementSyntax { Expression: LiteralExpressionSyntax })
            .ToList();
    }

    private MethodDeclarationSyntax CreateMethodDeclaration(string methodName, List<StatementSyntax> statements)
    {
        return MethodDeclaration(PredefinedType(Token(SyntaxKind.VoidKeyword)), methodName)
            .AddModifiers(Token(SyntaxKind.PublicKeyword))
            .AddAttributeLists(AttributeList(SingletonSeparatedList(
                Attribute(IdentifierName(TestAttributeName))
            )))
            .WithBody(Block(statements));
    }

    private ExpressionStatementSyntax CreateCommentStatement(string comment)
    {
        return ExpressionStatement(
            LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(comment))
        );
    }

    private List<StatementSyntax> CreateArrangeStatements(MethodInfo methodInfo, List<DependencyInfo> dependencies)
    {
        var statements = new List<StatementSyntax>();
        List<LocalDeclarationStatementSyntax> parameterDeclarations = CreateParameterDeclarations(methodInfo);
        statements.AddRange(parameterDeclarations);

        List<StatementSyntax> mockSetups = CreateMockSetups(dependencies);
        statements.AddRange(mockSetups);

        return statements;
    }

    private List<LocalDeclarationStatementSyntax> CreateParameterDeclarations(MethodInfo methodInfo)
    {
        return methodInfo.Parameters
            .Select(p => CreateParameterDeclaration(p))
            .ToList();
    }

    private LocalDeclarationStatementSyntax CreateParameterDeclaration(ParameterInfo param)
    {
        ExpressionSyntax defaultValue = GetDefaultValue(param.Type);

        return LocalDeclarationStatement(
            VariableDeclaration(IdentifierName(param.Type))
                .AddVariables(VariableDeclarator(Identifier(param.Name))
                    .WithInitializer(EqualsValueClause(defaultValue)))
        );
    }

    private List<StatementSyntax> CreateMockSetups(List<DependencyInfo> dependencies)
    {
        var mockSetupBuilder = new MockSetupBuilder();

        foreach (DependencyInfo dependency in dependencies)
        {
            AddMockSetupsForDependency(mockSetupBuilder, dependency);
        }

        return mockSetupBuilder.Build();
    }

    private void AddMockSetupsForDependency(MockSetupBuilder builder, DependencyInfo dependency)
    {
        foreach (MethodSignature method in dependency.Methods)
        {
            builder.AddSetup(dependency, method);
        }
    }

    private List<StatementSyntax> CreateActStatements(MethodInfo methodInfo)
    {
        var statements = new List<StatementSyntax>();
        SeparatedSyntaxList<ArgumentSyntax> arguments = BuildArgumentList(methodInfo);
        InvocationExpressionSyntax invocation = BuildMethodInvocation(arguments, methodInfo.Name);

        if (methodInfo.ReturnType != "void")
        {
            StatementSyntax assignment = CreateVariableAssignment(methodInfo.ReturnType, ActualVariableName, invocation);
            statements.Add(assignment);
        }
        else
        {
            statements.Add(ExpressionStatement(invocation));
        }

        return statements;
    }

    private SeparatedSyntaxList<ArgumentSyntax> BuildArgumentList(MethodInfo methodInfo)
    {
        return SeparatedList<ArgumentSyntax>(
            methodInfo.Parameters.Select(p => Argument(IdentifierName(p.Name)))
        );
    }

    private InvocationExpressionSyntax BuildMethodInvocation(SeparatedSyntaxList<ArgumentSyntax> arguments, string methodName)
    {
        return InvocationExpression(
            MemberAccessExpression(
                SyntaxKind.SimpleMemberAccessExpression,
                IdentifierName(TestClassFieldName),
                IdentifierName(methodName)
            )
        ).WithArgumentList(ArgumentList(arguments));
    }

    private LocalDeclarationStatementSyntax CreateVariableAssignment(string type, string name, ExpressionSyntax value)
    {
        return LocalDeclarationStatement(
            VariableDeclaration(IdentifierName(type))
                .AddVariables(VariableDeclarator(Identifier(name))
                    .WithInitializer(EqualsValueClause(value)))
        );
    }

    private List<StatementSyntax> CreateAssertStatements(MethodInfo methodInfo, List<DependencyInfo> dependencies)
    {
        var statements = new List<StatementSyntax>();

        if (methodInfo.ReturnType != "void")
        {
            List<StatementSyntax> returnAssertions = CreateReturnAssertions(methodInfo);
            statements.AddRange(returnAssertions);
        }

        List<StatementSyntax> mockVerifications = CreateMockVerifications(dependencies);
        statements.AddRange(mockVerifications);

        ExpressionStatementSyntax failStatement = CreateFailStatement();
        statements.Add(failStatement);

        return statements;
    }

    private List<StatementSyntax> CreateReturnAssertions(MethodInfo methodInfo)
    {
        var statements = new List<StatementSyntax>();
        ExpressionSyntax defaultValue = GetDefaultValue(methodInfo.ReturnType);
        StatementSyntax expectedDeclaration = CreateVariableAssignment(methodInfo.ReturnType, ExpectedVariableName, defaultValue);
        statements.Add(expectedDeclaration);

        ExpressionSyntax assertInvocation = BuildAssertThatInvocation();
        statements.Add(ExpressionStatement(assertInvocation));

        return statements;
    }

    private InvocationExpressionSyntax BuildAssertThatInvocation()
    {
        return InvocationExpression(
            MemberAccessExpression(
                SyntaxKind.SimpleMemberAccessExpression,
                IdentifierName("Assert"),
                IdentifierName("That")
            )
        ).WithArgumentList(ArgumentList(SeparatedList(new[]
        {
            Argument(IdentifierName(ActualVariableName)),
            Argument(
                InvocationExpression(
                    MemberAccessExpression(
                        SyntaxKind.SimpleMemberAccessExpression,
                        IdentifierName("Is"),
                        IdentifierName("EqualTo")
                    )
                ).WithArgumentList(ArgumentList(
                    SingletonSeparatedList(Argument(IdentifierName(ExpectedVariableName)))
                ))
            )
        })));
    }

    private List<StatementSyntax> CreateMockVerifications(List<DependencyInfo> dependencies)
    {
        var mockSetupBuilder = new MockSetupBuilder();

        foreach (DependencyInfo dependency in dependencies)
        {
            AddMockVerificationsForDependency(mockSetupBuilder, dependency);
        }

        return mockSetupBuilder.Build();
    }

    private void AddMockVerificationsForDependency(MockSetupBuilder builder, DependencyInfo dependency)
    {
        foreach (MethodSignature method in dependency.Methods)
        {
            builder.AddVerify(dependency, method);
        }
    }

    private ExpressionStatementSyntax CreateFailStatement()
    {
        InvocationExpressionSyntax invocation = InvocationExpression(
            MemberAccessExpression(
                SyntaxKind.SimpleMemberAccessExpression,
                IdentifierName("Assert"),
                IdentifierName("Fail")
            )
        ).WithArgumentList(ArgumentList(
            SingletonSeparatedList(Argument(
                LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(FailMessage))
            ))
        ));

        return ExpressionStatement(invocation);
    }

    private static LiteralExpressionSyntax GetDefaultValue(string type)
    {
        return type switch
        {
            "int" => LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(0)),
            "long" => LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(0L)),
            "double" => LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(0.0)),
            "float" => LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(0.0f)),
            "string" => LiteralExpression(SyntaxKind.StringLiteralExpression, Literal("")),
            "bool" => LiteralExpression(SyntaxKind.FalseLiteralExpression),
            _ => LiteralExpression(SyntaxKind.NullLiteralExpression)
        };
    }
}